"use server";

// All projects are declared statically — this works on Vercel (fs does not).
// To add a new image: upload to /public/image/<folder>/ and add an entry here.

type Cat = "All" | "Social Media" | "Banners" | "Logos" | "Packaging";

export interface Project {
  id: string;
  title: string;
  client: string;
  cat: Cat;
  tags: string[];
  img: string;
}

const PROJECTS: Project[] = [
  // ── Social Media (111 posters) ────────────────────────────────────────────
  { id: "p1",   title: "Fantastic Friday",       client: "The Cycle Gap",  cat: "Social Media", tags: ["#poster","#event","#nightlife"], img: "/image/poster/Poster%20(1).jpeg" },
  { id: "p2",   title: "Event Night",             client: "The Cycle Gap",  cat: "Social Media", tags: ["#poster","#socialmedia"],        img: "/image/poster/Poster%20(2).jpeg" },
  { id: "p3",   title: "Weekend Special",         client: "Brand Campaign", cat: "Social Media", tags: ["#poster","#promotion"],          img: "/image/poster/Poster%20(3).jpeg" },
  { id: "p4",   title: "Offer Post",              client: "Brand Campaign", cat: "Social Media", tags: ["#socialmedia","#offer"],         img: "/image/poster/Poster%20(4).jpeg" },
  { id: "p5",   title: "Brand Campaign",          client: "Retail Client",  cat: "Social Media", tags: ["#socialmedia","#branding"],      img: "/image/poster/Poster%20(5).jpeg" },
  { id: "p6",   title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(6).jpeg" },
  { id: "p7",   title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(7).jpeg" },
  { id: "p8",   title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(8).jpeg" },
  { id: "p9",   title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(9).jpeg" },
  { id: "p10",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(10).jpeg" },
  { id: "p11",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(11).jpeg" },
  { id: "p12",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(12).jpeg" },
  { id: "p13",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(13).jpeg" },
  { id: "p14",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(14).jpeg" },
  { id: "p15",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(15).jpeg" },
  { id: "p16",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(16).jpeg" },
  { id: "p17",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(17).jpeg" },
  { id: "p18",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(18).jpeg" },
  { id: "p19",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(19).jpeg" },
  { id: "p20",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(20).jpeg" },
  { id: "p21",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(21).jpeg" },
  { id: "p22",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(22).jpeg" },
  { id: "p23",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(23).jpeg" },
  { id: "p24",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(24).jpeg" },
  { id: "p25",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(25).jpeg" },
  { id: "p26",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(26).jpeg" },
  { id: "p27",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(27).jpeg" },
  { id: "p28",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(28).jpeg" },
  { id: "p29",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(29).jpeg" },
  { id: "p30",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(30).jpeg" },
  { id: "p31",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(31).jpeg" },
  { id: "p32",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(32).jpeg" },
  { id: "p33",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(33).jpeg" },
  { id: "p34",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(34).jpeg" },
  { id: "p35",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(35).jpeg" },
  { id: "p36",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(36).jpeg" },
  { id: "p37",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(37).jpeg" },
  { id: "p38",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(38).jpeg" },
  { id: "p39",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(39).jpeg" },
  { id: "p40",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(40).jpeg" },
  { id: "p41",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(41).jpeg" },
  { id: "p42",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(42).jpeg" },
  { id: "p43",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(43).jpeg" },
  { id: "p44",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(44).jpeg" },
  { id: "p45",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(45).jpeg" },
  { id: "p46",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(46).jpeg" },
  { id: "p47",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(47).jpeg" },
  { id: "p48",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(48).jpeg" },
  { id: "p49",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(49).jpeg" },
  { id: "p50",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(50).jpeg" },
  { id: "p51",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(51).jpeg" },
  { id: "p52",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(52).jpeg" },
  { id: "p53",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(53).jpeg" },
  { id: "p54",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(54).jpeg" },
  { id: "p55",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(55).jpeg" },
  { id: "p56",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(56).jpeg" },
  { id: "p57",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(57).jpeg" },
  { id: "p58",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(58).jpeg" },
  { id: "p59",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(59).jpeg" },
  { id: "p60",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(60).jpeg" },
  { id: "p61",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(61).jpeg" },
  { id: "p62",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(62).jpeg" },
  { id: "p63",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(63).jpeg" },
  { id: "p64",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(64).jpeg" },
  { id: "p65",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(65).jpeg" },
  { id: "p66",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(66).jpeg" },
  { id: "p67",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(67).jpeg" },
  { id: "p68",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(68).jpeg" },
  { id: "p69",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(69).jpeg" },
  { id: "p70",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(70).jpeg" },
  { id: "p71",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(71).jpeg" },
  { id: "p72",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(72).jpeg" },
  { id: "p73",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(73).jpeg" },
  { id: "p74",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(74).jpeg" },
  { id: "p75",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(75).jpeg" },
  { id: "p76",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(76).jpeg" },
  { id: "p77",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(77).jpeg" },
  { id: "p78",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(78).jpeg" },
  { id: "p79",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(79).jpeg" },
  { id: "p80",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(80).jpeg" },
  { id: "p81",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(81).jpeg" },
  { id: "p82",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(82).jpeg" },
  { id: "p83",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(83).jpeg" },
  { id: "p84",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(84).jpeg" },
  { id: "p85",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(85).jpeg" },
  { id: "p86",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(86).jpeg" },
  { id: "p87",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(87).jpeg" },
  { id: "p88",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(88).jpeg" },
  { id: "p89",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(89).jpeg" },
  { id: "p90",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(90).jpeg" },
  { id: "p91",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(91).jpeg" },
  { id: "p92",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(92).jpeg" },
  { id: "p93",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(93).jpeg" },
  { id: "p94",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(94).jpeg" },
  { id: "p95",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(95).jpeg" },
  { id: "p96",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(96).jpeg" },
  { id: "p97",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(97).jpeg" },
  { id: "p98",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(98).jpeg" },
  { id: "p99",  title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(99).jpeg" },
  { id: "p100", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(100).jpeg" },
  { id: "p101", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(101).jpeg" },
  { id: "p102", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(102).jpeg" },
  { id: "p103", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(103).jpeg" },
  { id: "p104", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(104).jpeg" },
  { id: "p105", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(105).jpeg" },
  { id: "p106", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(106).jpeg" },
  { id: "p107", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(107).jpeg" },
  { id: "p108", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(108).jpeg" },
  { id: "p109", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(109).jpeg" },
  { id: "p110", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(110).jpeg" },
  { id: "p111", title: "Social Media Campaign",   client: "Seyon Archive",  cat: "Social Media", tags: ["#social","#poster"],             img: "/image/poster/Poster%20(111).jpeg" },

  // ── Banners (26) ──────────────────────────────────────────────────────────
  { id: "b1",  title: "Baking Essentials", client: "E-Commerce",    cat: "Banners", tags: ["#banner","#ecommerce","#food"], img: "/image/banner/Banner%20(1).jpeg" },
  { id: "b2",  title: "Product Banner",    client: "Online Store",  cat: "Banners", tags: ["#banner","#product"],           img: "/image/banner/Banner%20(2).jpeg" },
  { id: "b3",  title: "Sale Banner",       client: "Retail Brand",  cat: "Banners", tags: ["#banner","#sale","#ecommerce"], img: "/image/banner/Banner%20(3).jpeg" },
  { id: "b4",  title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(4).jpeg" },
  { id: "b5",  title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(5).jpeg" },
  { id: "b6",  title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(6).jpeg" },
  { id: "b7",  title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(7).jpeg" },
  { id: "b8",  title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(8).jpeg" },
  { id: "b9",  title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(9).jpeg" },
  { id: "b10", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(10).jpeg" },
  { id: "b11", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(11).jpeg" },
  { id: "b12", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(12).jpeg" },
  { id: "b13", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(13).jpeg" },
  { id: "b14", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(14).jpeg" },
  { id: "b15", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(15).jpeg" },
  { id: "b16", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(16).jpeg" },
  { id: "b17", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(17).jpeg" },
  { id: "b18", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(18).jpeg" },
  { id: "b19", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(19).jpeg" },
  { id: "b20", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(20).jpeg" },
  { id: "b21", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(21).jpeg" },
  { id: "b22", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(22).jpeg" },
  { id: "b23", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(23).jpeg" },
  { id: "b24", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(24).jpeg" },
  { id: "b25", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(25).jpeg" },
  { id: "b26", title: "Digital Banner",    client: "Seyon Archive", cat: "Banners", tags: ["#banner","#digital"],           img: "/image/banner/Banner%20(26).jpeg" },

  // ── Logos (16) ────────────────────────────────────────────────────────────
  { id: "l1",  title: "Wild Flour",              client: "Wild Flour",      cat: "Logos", tags: ["#logo","#branding","#packaging"], img: "/image/logo/Wild%20Flour%20Mockup.jpg" },
  { id: "l2",  title: "Zen Enterprises",         client: "Zen Enterprises", cat: "Logos", tags: ["#logo","#identity","#branding"],  img: "/image/logo/Zen%20Enterprises%20Logo-04.jpg" },
  { id: "l3",  title: "Conectr",                 client: "Conectr",         cat: "Logos", tags: ["#logo","#tech","#startup"],       img: "/image/logo/Conectr.png" },
  { id: "l4",  title: "Adyar Vaishnava's",       client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/Adyar%20Vaishnava's%20Logo-01.jpg" },
  { id: "l5",  title: "Brand Identity",          client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/EM_1.png" },
  { id: "l6",  title: "Every Body Can Yoga",     client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#wellness","#branding"],  img: "/image/logo/Every%20Body%20Can%20Yoga%20Logo.jpg" },
  { id: "l7",  title: "Everybody Can Yoga",      client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#wellness","#branding"],  img: "/image/logo/Everybody%20Can%20Yoga%20Logo-01.jpg" },
  { id: "l8",  title: "Medijourn",               client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#medical","#branding"],   img: "/image/logo/MEDIJOURN.png" },
  { id: "l9",  title: "NR Logo",                 client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/NR%20Logo.png" },
  { id: "l10", title: "OCD",                     client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/OCD.png" },
  { id: "l11", title: "SG10",                    client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/SG10%20Logo.jpg" },
  { id: "l12", title: "SM Logo",                 client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/SM%20Logo-03.jpg" },
  { id: "l13", title: "Smart Check",             client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#tech","#branding"],      img: "/image/logo/Smart%20Check%20Logo.png" },
  { id: "l14", title: "Vishvas",                 client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/VISHVAS.png" },
  { id: "l15", title: "Vishvas Outline",         client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/vishvas%20out%20.png" },
  { id: "l16", title: "Brand Identity",          client: "Seyon Archive",   cat: "Logos", tags: ["#logo","#branding"],              img: "/image/logo/logo%20file-12.png" },

  // ── Packaging (4) ─────────────────────────────────────────────────────────
  { id: "k1",  title: "Agni Masala Brand",  client: "Agni Masala", cat: "Packaging", tags: ["#packaging","#label","#branding"], img: "/image/label/Agni%20Masala%20Branding-12.jpg" },
  { id: "k2",  title: "Agni Masala Series", client: "Agni Masala", cat: "Packaging", tags: ["#packaging","#label"],             img: "/image/label/Agni%20Masala%20Branding-16.jpg" },
  { id: "k3",  title: "Plumoeasy",          client: "Plumoeasy",   cat: "Packaging", tags: ["#packaging","#mockup","#label"],   img: "/image/label/Plumoeasy%20Mockup-1.jpg" },
  { id: "k4",  title: "Plumoeasy Vol.2",    client: "Plumoeasy",   cat: "Packaging", tags: ["#packaging","#mockup","#label"],   img: "/image/label/Plumoeasy%20Mockup-2.jpg" },
];

export async function getDynamicWorkProjects(): Promise<Project[]> {
  return [...PROJECTS].sort(() => Math.random() - 0.5);
}
